import React, { Component } from 'react';
import '../App.css';

class Home extends Component {
  render(){ 
    return (
      <div>
        <h1 className='Home-header'>Welcome to Cat House Percussion!</h1>
        <div className='Home-body'>
          <p>Lorizzle ipsizzle dolor gizzle amet, we gonna chung adipiscing cool. Nullizzle sapizzle velizzle, ass volutpizzle, suscipizzle quis, izzle mah nizzle, dizzle. Pellentesque gangster tortor. Things erizzle. Fusce at boofron dapibus turpis tempus i'm in the shizzle. Maurizzle crackalackin nibh fizzle pizzle. Doggy break yo neck, yall daahng dawg. Pellentesque shizzlin dizzle rhoncizzle nisi. Its fo rizzle hizzle habitasse platea dictumst. Boom shackalack dapibizzle. Nizzle tellus urna, pretizzle cool, mattizzle izzle, eleifend vitae, shiznit. Dizzle suscipizzle. Integizzle semper velizzle sizzle i'm in the shizzle.
          Etizzle fo shizzle urna nisl. Boom shackalack quizzle shiznit. Mammasay mammasa mamma oo sa sheezy, ipsizzle break yo neck, yall malesuada shizzlin dizzle, nulla purizzle euismizzle sheezy, izzle luctizzle metus yo mamma izzle dang. Vivamizzle ullamcorper, sure my shizz varizzle phat, nibh nunc ultricizzle turpis, izzle pimpin' leo elizzle in dolizzle. Mauris shizzle my nizzle crocodizzle, orci dang volutpat doggy, sizzle augue tellivizzle shiz, izzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle enizzle gangsta izzle nisl. Owned yo velizzle daahng dawg orci eleifend fo shizzle. Phasellizzle nizzle own yo'. Curabitizzle non shiznit hizzle pede nizzle facilisizzle. Da bomb sapien nulla, iaculizzle ghetto, molestie gangster, egestizzle a, eros. Bizzle vitae turpis own yo' nibh bibendizzle consequat. Nam pulvinizzle consectetuer fo shizzle. Aliquizzle dizzle volutpat. Nunc you son of a bizzle leo izzle bling bling pretium my shizz. Cras nec lacizzle rizzle dui shiz . Shiznit nisl. Stuff et urna. Check it out laoreet ipsizzle sheezy . You son of a bizzle get down get down fizzle.
          Curabitizzle et dizzle da bomb gizzle fo shizzle crunk. Suspendisse potenti. Morbi odio. Vivamus sure. Things orci. You son of a bizzle maurizzle shit, interdizzle dope, feugiat sit amizzle, malesuada izzle, pede. Gizzle uhuh ... yih!. Vestibulum orci mi, phat izzle, sagittis ass, adipiscing sempizzle, cool. Crizzle izzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle. Aliquam volutpat felizzle vizzle orci. Cras rizzle justo pot purizzle sodales ornare. </p
          ><p>Shizznit venenatis crackalackin bizzle sure. Mammasay mammasa mamma oo sa urna. Suspendisse crunk placerizzle lacizzle. Curabitur mofo ante. Nunc pharetra, shit check it out fizzle hendrerizzle, uhuh ... yih! felizzle elementum sem, in aliquizzle sure felizzle luctus shit. Nizzle a nisl. You son of a bizzle doggy taciti dizzle izzle i saw beyonces tizzles and my pizzle went crizzle torquent fizzle conubia nostra, pizzle its fo rizzle hymenizzle. Aliquizzle interdum, neque gangsta elementum nonummy, ass its fo rizzle viverra leo, get down get down boom shackalack sizzle crazy fo shizzle sizzle.
          Shut the shizzle up a we gonna chung sed check it out hendrerit hizzle. Aenean izzle est. Sheezy fo shizzle black, viverra shiznit, facilisizzle id, phat yo, erizzle. Vestibulum ante i saw beyonces tizzles and my pizzle went crizzle ghetto faucibizzle orci you son of a bizzle pizzle ultricizzle shiz cubilia Dizzle; Donizzle gizzle. Integer faucibus. Maecenizzle pharetra brizzle quizzle. Vivamizzle rutrum aliquizzle fo shizzle. Sed facilisis. Maurizzle doggy nulla, crunk izzle, scelerisque vel, yo mamma izzle, magna.
          Integer ac metus gangsta arcu interdizzle aliquam. Quisque posuere. Stuff nizzle ante. Cool shiz pede, nizzle izzle, owned ut, euismod quizzle, massa. Vestibulizzle feugiat. Boofron sure ultricies yippiyo. Quisque vulputate, orci a suscipizzle brizzle, enizzle my shizz doggy fo shizzle mah nizzle fo rizzle, mah home g-dizzle, izzle tellivizzle dizzle nulla nec metizzle. Maecenizzle i'm in the shizzle sollicitudizzle hizzle. Quisque neque maurizzle, phat pizzle, malesuada id, bibendizzle varizzle, break it down. Dizzle boom shackalack, ligula crunk mammasay mammasa mamma oo sa we gonna chung, velizzle nizzle posuere nisl, a boom shackalack justo lorem my shizz fo shizzle my shizz. Gizzle izzle nizzle odio shiznit fizzle. Quisque aliquet tempizzle sheezy. Nam shiz hendrerizzle mauris. For sure vehicula. Fizzle placerat leo a mi. Daahng dawg pellentesque. You son of a bizzle hizzle habitasse platea dictumst. Crizzle nizzle leo shit diam check out this eleifend. Break it down erizzle , pulvinar quis, fringilla check it out, consectetizzle nec, nisl. Morbi vizzle crazy izzle i saw beyonces tizzles and my pizzle went crizzle tempus fringilla.
          Crizzle aliquam pede we gonna chung mi. Bow wow wow izzle natoque penatibus izzle magnizzle funky fresh parturient things, nascetizzle shut the shizzle up mus. Ut purizzle diam, molestie pot, convallizzle stuff, sollicitudin sheezy, urna. Mauris viverra da bomb shizznit fo shizzle. Donizzle shut the shizzle up. Dang augue orci, uhuh ... yih! a, aliquizzle a, gangsta izzle, fizzle. Crizzle gangster, nulla sit amizzle owned gravida, dui lectus ornare enizzle, a hendrerizzle gizzle est scelerisque velizzle. Phat quizzle odio. Nizzle sizzle dolizzle gizzle metizzle. Gizzle fizzle.</p>
        </div>
      </div>
    )
  }
}

export default Home;